### ISSUE TITLE
Bumpy road effect

### ISSUE THREAD

**Issue by chirudeep001** [tud-hri/logitech_steering_wheel#3]
Hi,
when i run the GUI code i could see the bumpy road effect feedback in the steering wheel, but when i run the test_script i could not see any bumpy road effect in the steering wheel but the scripts runs successfully and shows steering wheel connected.

if i update the code to play_slippery_road_effect i could not see any effect on the steering wheel.

Thank you

**Comment by OlgerSiebinga** [comment]
Hi @chirudeep001,

The Logitech SDK needs an active window to interact with the steering wheel. The GUI test script opens a window and uses the handle to that window while the bare bones test script tries to "highjack"  the window from which you are running that script. 

You could try to run the bare test script from an application with a valid window handle, that might work. In that case make sure the window stays active! If you select another window, the connection will break.  Otherwise, you could try to implement the test script code in your own application and supply the window handle to you're active window. 

hope this helps!
